print "this is new fileee....."
print "this is new fileee....."
print "this is new fileee....."
print "this is new fileee....."
print "this is new fileee....."
print "newlinessssss............."
print "newlinessssss............."
print "newlinessssss............."
print "newlinessssss............."
print "newlinessssss............."
print "newlinessssss............."
